"""The corpus writes here now.

Migration 29e0c9733097 made room for the analysed corpus and proved the
counting: identical to Python on all 169,155 sentences, 10.04s of CPU down
to 2.18s. This is what it takes for `corpus/store.py` to actually live here
rather than keep a copy.

Three things.

`build_meta` comes across, because it describes these rows and nothing else
— which rules produced a build, when, and with which spaCy. Leaving it in
SQLite would mean asking one database whether another one's data is stale.

`corpus_sentence.id` gets an identity. The table was loaded with explicit ids
carried over from SQLite, so it needed none; `_write` inserts new sentences
and reads the id back, so it needs one now. Same reasoning as 9863bcf8177b,
including `BY DEFAULT` over `ALWAYS` — a reload still supplies its own ids.

`unit_count` becomes a materialized view instead of a table. It exists
because grouping 1.74M unit rows took 2.3 seconds in SQLite; here that query
is 208ms, so the original reason is gone — but reading a precomputed answer
is still 103ms, and the difference is paid on every page that ranks units.
A view keeps the saving without the thing that made the table objectionable:
the definition lives in the database, and refreshing it is one statement
rather than DELETE-plus-INSERT written out in Python and kept in step by
hand. The unique index is what lets that refresh run CONCURRENTLY, so a
rebuild does not lock out readers.

Revision ID: 6f2a1c84bb70
Revises: 29e0c9733097
Create Date: 2026-09-11
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "6f2a1c84bb70"
down_revision = "29e0c9733097"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "build_meta",
        sa.Column("build", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("made_at", sa.Text(), nullable=False),
        # The parser that produced it, kept apart from the rules hash: a
        # different spaCy is worth saying out loud, but it is not a reason
        # for a machine that only serves these rows to distrust them.
        sa.Column("packages", sa.Text(), nullable=False,
                  server_default=sa.text("''")),
        sa.PrimaryKeyConstraint("build", name="build_meta_pkey"),
    )

    op.execute('ALTER TABLE corpus_sentence ALTER COLUMN id'
               ' ADD GENERATED BY DEFAULT AS IDENTITY')
    op.execute("""
        SELECT setval(pg_get_serial_sequence('corpus_sentence', 'id'),
                      coalesce(max(id), 0) + 1, false) FROM corpus_sentence
    """)

    op.execute("""
        CREATE MATERIALIZED VIEW corpus_unit_count AS
        SELECT s.build, u.kind, u.key, count(*)::int AS said
          FROM corpus_unit u
          JOIN corpus_sentence s ON s.id = u.sentence_id
         GROUP BY s.build, u.kind, u.key
    """)
    # Required for REFRESH ... CONCURRENTLY, and it is also the read path:
    # every caller filters by build and groups by unit.
    op.execute("CREATE UNIQUE INDEX ix_corpus_unit_count"
               " ON corpus_unit_count (build, kind, key)")


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW IF EXISTS corpus_unit_count")
    op.execute("ALTER TABLE corpus_sentence ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.drop_table("build_meta")
