"""Give back the keys, now that we write here.

The first migration left the sequences out, and said why: every row arrived
from `sync-catalogue` with an id already on it, so a sequence would have been
a thing to reset after every sync and nothing else. It also said what would
change that — "if this project ever writes its own rows, that is a later
migration with a reason attached".

This is that migration. The decision was to own the catalogue outright rather
than read a copy of someone else's, so ingestion now writes here, and
language-app's scraper assigns no keys: every statement omits the primary key
and reads it back.

    INSERT INTO sentence (video_id, start_time, ...) ... RETURNING sentence_id
    INSERT INTO grammar_rule (rule, language) VALUES (%s, %s) RETURNING rule_id

Without a default those fail on the NOT NULL, so the five surrogate keys get
identity columns.

`BY DEFAULT`, not `ALWAYS`. `ALWAYS` rejects an explicit value, and the sync
supplies explicit ids for every row it copies — it would refuse the one thing
this schema is filled by.

`video.video_id` is deliberately left alone. Upstream gives it a sequence,
but the column is text and holds a YouTube id, and the scraper has always
supplied it; the sequence there was vestigial and copying it would only
suggest a key this database might generate, which it must not.

After setting each column up, its sequence is moved past the rows already
copied in. A fresh identity starts at 1, and 302,007 sentences are already
sitting on ids 1 upward — the first insert would collide immediately.

Revision ID: 9863bcf8177b
Revises: dd0d9cf4b307
Create Date: 2026-09-11
"""
from __future__ import annotations

from alembic import op

revision = "9863bcf8177b"
down_revision = "dd0d9cf4b307"
branch_labels = None
depends_on = None

# The surrogate keys the scraper leaves for the database to assign.
KEYS: tuple[tuple[str, str], ...] = (
    ("channel", "id"),
    ("sentence", "sentence_id"),
    ("word_table", "word_id"),
    ("phrase_table", "phrase_id"),
    ("grammar_rule", "rule_id"),
)


def upgrade() -> None:
    for table, column in KEYS:
        op.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{column}"'
                   f" ADD GENERATED BY DEFAULT AS IDENTITY")
        # Past whatever the sync already put there. `is_called = false` so the
        # next value handed out is the number given, not the one after it,
        # which keeps the empty-table case (max is null) starting at 1.
        op.execute(f"""
            SELECT setval(pg_get_serial_sequence('{table}', '{column}'),
                          coalesce(max("{column}"), 0) + 1, false)
              FROM "{table}"
        """)


def downgrade() -> None:
    for table, column in KEYS:
        op.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{column}"'
                   f" DROP IDENTITY IF EXISTS")
